/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#fcfaf7',
        'on-background': '#423d38',
        surface: '#f3f4f6',
        'surface-soft': '#edebe9',
        'surface-elevated': '#ffffff',
        'on-surface': '#423d38',
        'on-surface-muted': '#797067',
        outline: '#e3e0dd',
        'outline-strong': '#d1d5dc',
        primary: '#fe6e00',
        'primary-strong': '#ff6b00',
        'primary-warm': '#ffb74d',
        'primary-focus': '#f97015',
        'on-primary': '#ffffff',
        'shell-base': '#000000',
        'on-shell': '#ffffff',
        'shell-border': '#ffffff',
        success: '#00c758',
        warning: '#edb200',
        danger: '#fb2c36',
        info: '#3080ff',
        'status-mock-bg': '#fef9c2',
        'status-mock-fg': '#874b00',
        'status-planned-bg': '#f3f4f6',
        'status-planned-fg': '#364153',
        'status-development-bg': '#dbeafe',
        'status-development-fg': '#1447e6',
        'status-integrated-bg': '#f3e8ff',
        'status-integrated-fg': '#8200da',
        'status-production-bg': '#dcfce7',
        'status-production-fg': '#016630',
        'dark-background': '#413830',
        'dark-surface': '#4a423a',
        'dark-on-surface': '#fafaf9',
        'dark-on-surface-muted': '#b9b3ac',
      },
      fontFamily: {
        sans: ['ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      fontSize: {
        'display-hero': ['6rem', { lineHeight: '1', letterSpacing: '-0.025em', fontWeight: '600' }],
        'headline-xl': ['2rem', { lineHeight: '2.5rem', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-lg': ['1.5rem', { lineHeight: '2rem', fontWeight: '700' }],
        'title-md': ['1.125rem', { lineHeight: '1.75rem', fontWeight: '700' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem', fontWeight: '400' }],
        'body-md': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'body-sm': ['0.8125rem', { lineHeight: '1rem', fontWeight: '700' }],
        'label-md': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '500' }],
        'label-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.05em', fontWeight: '600' }],
        'code-sm': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '400' }],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '32px',
        '3xl': '40px',
        '4xl': '64px',
        'container-padding': '32px',
        'shell-header-height': '64px',
        'shell-sidebar-expanded': '256px',
        'shell-sidebar-collapsed': '64px',
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        pill: '9999px',
      },
      maxWidth: {
        container: '1400px',
      },
      boxShadow: {
        subtle: '0 1px 3px rgba(0, 0, 0, 0.10), 0 1px 2px rgba(0, 0, 0, 0.06)',
        raised: '0 4px 12px rgba(0, 0, 0, 0.12)',
        dialog: '0 20px 25px rgba(0, 0, 0, 0.10), 0 8px 10px rgba(0, 0, 0, 0.04)',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '200ms',
        slow: '300ms',
        panel: '500ms',
      },
      transitionTimingFunction: {
        standard: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      blur: {
        shell: '12px',
      },
    },
  },
  plugins: [],
}
